# Site settings
title: Personal Info
description: Pavel Shalagin personal info website
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "https://example.com" # the base hostname & protocol for your site

# Exclude files and directories from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .sass-cache
  - .jekyll-cache
  - _site
  - README.md

# Include additional files
include:
  - .well-known
  - images
