NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
VERSION = "2.0.0"

ACCOUNTS=[
    "GANVDGQOEN7UILIMTAJBIBBXXAEOPB2AJ7CAOFVGLSZK6DYWQ4CZMISH",
    "GCYZXHYYSDM6UCYNK6AEWRUJGCPIM2UTBCR2U7X6NRDQ4AQ3JCPIADOU",
    "GDIEPGDHOBBMQCUIT6SYADZPMY4XH7ETIUFGGCRD5J7L6TELV26O2OEL"
]

# Basic information about the issuing account
[DOCUMENTATION]
ORG_NAME = "MF Fund"
ORG_URL = "https://monte.wiki/en/MF_Fund"
ORG_LOGO = "https://pshalagin.github.io/images/stellar-logo.jpg"
ORG_DESCRIPTION = "A family fund of @pshalagin and @ikandrakhina."
ORG_PHYSICAL_ADDRESS = "Montelibero City, Pečurice, 85356, Montenegro"
ORG_OFFICIAL_EMAIL = "pshalagin+mtl@gmail.com"
#ORG_GITHUB = "pshalagin"

# Asset definitions
[[CURRENCIES]]
code = "PSY"
status = "live"
issuer = "GCYZXHYYSDM6UCYNK6AEWRUJGCPIM2UTBCR2U7X6NRDQ4AQ3JCPIADOU"
display_decimals = 0
is_asset_anchored = false
name = "Gestalt Consultation"
desc = "An equivalent of 1 hour of @pshalagin consultation services as a Gestalt therapist."
image = "https://pshalagin.github.io/images/stellar-logo-psy.jpg"

[[CURRENCIES]]
code = "PSD"
status = "live"
issuer = "GCYZXHYYSDM6UCYNK6AEWRUJGCPIM2UTBCR2U7X6NRDQ4AQ3JCPIADOU"
display_decimals = 0
is_asset_anchored = false
name = "IT Services"
desc = "An equivalent of 1 hour of @pshalagin consultation services as a software architect and backend developer."
image = "https://pshalagin.github.io/images/stellar-logo-psd.jpg"
