NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
VERSION = "2.0.0"

ACCOUNTS=[
    "GCYZXHYYSDM6UCYNK6AEWRUJGCPIM2UTBCR2U7X6NRDQ4AQ3JCPIADOU"
]

# Basic information about the issuing account
[DOCUMENTATION]
ORG_NAME = "Pavel Shalagin"
ORG_URL = "https://pshalagin.github.io"
ORG_LOGO = "https://pshalagin.github.io/images/stellar-logo.png"
ORG_DESCRIPTION = "Individual entrepreneur providing services in psychology, software development, and product management."
ORG_PHYSICAL_ADDRESS = "Montelibero City, Pečurice, 85356, Montenegro"
ORG_OFFICIAL_EMAIL = "pshalagin+mtl@gmail.com"
ORG_GITHUB = "pshalagin"

# Asset definitions
[[CURRENCIES]]
code = "PSY"
issuer = "GCYZXHYYSDM6UCYNK6AEWRUJGCPIM2UTBCR2U7X6NRDQ4AQ3JCPIADOU"
display_decimals = 0
is_asset_anchored = false
name = "Psychlogy Consultation"
desc = "An equivalent of 1 hour of Pavel's psychology consultation services as a Gestalt therapist."
image = "https://pshalagin.github.io/images/stellar-logo-psy.png"

[[CURRENCIES]]
code = "PSD"
issuer = "GCYZXHYYSDM6UCYNK6AEWRUJGCPIM2UTBCR2U7X6NRDQ4AQ3JCPIADOU"
display_decimals = 0
is_asset_anchored = false
name = "Software Design and Development"
desc = "An equivalent of 1 hour of Pavel's consultation services as a software architect and backend developer."
image = "https://pshalagin.github.io/images/stellar-logo-psd.png"

# [[CURRENCIES]]
# code = "PSM"
# issuer = "GCYZXHYYSDM6UCYNK6AEWRUJGCPIM2UTBCR2U7X6NRDQ4AQ3JCPIADOU"
# display_decimals = 0
# name = "Product and Project Management"
# desc = ""
